apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: vt-voting-app-db-dep
spec:
  selector:
    matchLabels:
      app: vt-voting-app-db
  template:
    metadata:
      name: vt-voting-app-db
      labels:
        app: vt-voting-app-db
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
  replicas: 1    
    