apiVersion: v1
kind: Service
metadata:
  name: result-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      name: resultservice
      nodePort: 31001
  selector:
    app: vt-result-app